name: Compilation Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
       npm install
       npm run compile
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: UnstableBind-dev
        path: bin/saladbind/*
