name: Compilation Test

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ matrix.node-version }}
        
    - run: |
       npm install
       npm run compile
       
    - name: Upload a Build Artifact [Linux]
      uses: actions/upload-artifact@v3
      with:
        name: saladbind-linux
        path: bin/saladbind-linux

    - name: Upload a Build Artifact [MacOS]
      uses: actions/upload-artifact@v3
      with:
        name: saladbind-macos
        path: bin/saladbind-macos
        
      
    - name: Upload a Build Artifact [Windows]
      uses: actions/upload-artifact@v3
      with:
        name: saladbind-win
        path: bin/saladbind-win.exe
