name: DAG size updater

on:
  schedule:
    - cron: '* * 1/14 * *'
  workflow_dispatch:

jobs:
  github-actions:
    name: 🪸 DAG size updater - GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAG_UPDATER }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run update script
        run: |
            npm install node-fetch --no-save
            node internal/alfurDagUpdater
      - name: Import GPG key
        run: |
          echo "$GPG_KEY" | gpg --batch --import
        env:
          GPG_KEY: ${{ secrets.COLLISIONBOT_SIGN }}
      - name: Configuration & Push
        run: |
          echo '#!/bin/bash' >> $GITHUB_WORKSPACE/gpg.sh
          echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> $GITHUB_WORKSPACE/gpg.sh
          chmod +x $GITHUB_WORKSPACE/gpg.sh
          git config gpg.program $GITHUB_WORKSPACE/gpg.sh
          git config --global user.email "pun.experiment@gmail.com"
          git config --global user.name "CollisionBot"
          git config user.signingkey 4633555474DD3B1D
          git add internal/miners.json
          git commit -S -m "🔧 Weekly Maintenance: Update DAG sizes"
          git push
        env: 
          GPG_KEY_PASSPHRASE: ${{ secrets.COLLISIONBOT_PASS }}
