name: DAG size updater

on:
  schedule:
    - cron: '* * 1/14 * *'
  workflow_dispatch:

jobs:
  github-actions:
    name: 🪸 DAG size updater - GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAG_UPDATER }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run update script
        run: |
            npm install node-fetch --no-save
            node internal/alfurDagUpdater
      - name: Import GPG key
        run: echo $GPG_KEY | gpg --batch --import
        env:
          GPG_KEY: ${{ secrets.COLLISIONBOT_SIGN }}
      - name: Configuration
        run: |
          echo '#!/bin/bash' >> /tmp/gpg.sh
          echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
          chmod +x /tmp/gpg.sh
          git config gpg.program /tmp/gpg.sh
          git config user.signingkey 13D0B11B631937DE
        env: 
          GPG_KEY_PASSPHRASE: ${{ secrets.COLLISIONBOT_PASSPHRASE }}
      - name: Push
        run: |
            git add .
            git commit -S -m "🔧 Weekly Maintenance: Update DAG sizes"
            git push
