name: DAG size updater

on:
  schedule:
    - cron: '* * 1/14 * *'
  workflow_dispatch:

jobs:
  github-actions:
    name: 🪸 DAG size updater - GitHub Actions
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAG_UPDATER }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run update script
        run: |
            npm install node-fetch --no-save
            node internal/alfurDagUpdater
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.COLLISIONBOT_SIGN }}
          passphrase: ${{ secrets.COLLISIONBOT_PASSPHRASE }}
          trust_level: 5
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: if-asked
      - name: GPG Magic
        # I DON'T KNOW WHAT I'M DOING
        run: |
          rm -rf gpg.sh
          echo '#!/bin/bash' >> /tmp/gpg.sh
          echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
          chmod +x gpg.sh
          git config gpg.program gpg.sh
      - name: Push
        run: |
            git add .
            git commit -S -m "🔧 Weekly Maintenance: Update DAG sizes"
            git push
