name: Compile Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate changelog
        run: |
          gh api repos/EvadeMaster/UnstableBind/releases/generate-notes -f tag_name="${GITHUB_REF#refs/tags/}" -f target_commitish=main -q .body >> CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{secrets.DAG_UPDATER}}
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Compile
        run: |
            npm install
            npm run compile
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{ steps.changelog.outputs.content }}
          token: ${{ secrets.DAG_UPDATER}}
          files: |
            bin/saladbind-win.exe
            bin/saladbind-macos
            bin/saladbind-linux
